# -*- coding: utf-8 -*-
"""Week4_day6_dailyC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fMJ3IDh7Lrqt_9dqpE5uIA76W27U55ZJ

Apolo BARNABAS
Week4_day6_DailyCH
"""

from google.colab import files
uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

# ========================================
# Data Science Job Salary Analysis
# ========================================

# Import libraries
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.preprocessing import LabelEncoder

# ==========================================
# Step 1: Load the Dataset
# ==========================================

# Load the dataset. Based on the previous upload, the file is named 'ds_salaries.csv.csv'
df = pd.read_csv("ds_salaries.csv.csv")

print("First 5 rows:")
print(df.head())

print("\nDataset Shape:", df.shape)

# ==========================================
# Step 2: Normalize Salary Column
# ==========================================

# Check available salary columns
print("\nColumns:")
print(df.columns)

# Use salary_in_usd if salary doesn't exist
salary_column = "salary"

if salary_column not in df.columns:
    salary_column = "salary_in_usd"

# Min-Max Normalization
scaler = MinMaxScaler()

df["salary_normalized"] = scaler.fit_transform(
    df[[salary_column]]
)

print("\nNormalized Salary:")
print(df[[salary_column, "salary_normalized"]].head())

# ==========================================
# Step 3: Dimensionality Reduction using PCA
# ==========================================

# Select numerical columns only
numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns

# Create PCA input data
X = df[numeric_cols]

# Apply PCA to reduce to 2 components
pca = PCA(n_components=2)

X_pca = pca.fit_transform(X)

# Create PCA DataFrame
pca_df = pd.DataFrame(
    X_pca,
    columns=["Principal_Component_1",
             "Principal_Component_2"]
)

print("\nPCA Results:")
print(pca_df.head())

print("\nExplained Variance Ratio:")
print(pca.explained_variance_ratio_)

# ==========================================
# Step 4: Salary Statistics by Experience Level
# ==========================================

# If experience_level exists
if "experience_level" in df.columns:

    salary_stats = (
        df.groupby("experience_level")[salary_column]
        .agg(
            Average_Salary="mean",
            Median_Salary="median"
        )
        .reset_index()
    )

    print("\nAverage and Median Salary by Experience Level:")
    print(salary_stats)

else:
    print("\nColumn 'experience_level' not found.")

# ==========================================
# Optional: Decode Experience Levels
# ==========================================

experience_mapping = {
    "EN": "Junior",
    "MI": "Mid-level",
    "SE": "Senior",
    "EX": "Executive"
}

if "experience_level" in df.columns:
    df["experience_name"] = (
        df["experience_level"]
        .map(experience_mapping)
    )

    salary_stats_named = (
        df.groupby("experience_name")[salary_column]
        .agg(
            Average_Salary="mean",
            Median_Salary="median"
        )
        .reset_index()
    )

    print("\nSalary Statistics with Experience Names:")
    print(salary_stats_named)

"""### Importance of Min-Max Normalization

Normalization is an essential data preprocessing technique, especially when features have different scales or ranges. In the Data Science Job Salary dataset, salary values can vary significantly, ranging from tens of thousands to hundreds of thousands of dollars. Such large differences can negatively affect the performance of many machine learning algorithms.

Min-Max normalization transforms the salary values into a standardized range between 0 and 1 using the formula:

[
X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}
]

where:

* (X) is the original salary value,
* (X_{min}) is the minimum salary in the dataset,
* (X_{max}) is the maximum salary in the dataset.

By scaling all salary values to the same range, no single salary value dominates the learning process. This is particularly beneficial for machine learning algorithms such as K-Nearest Neighbors (KNN), Neural Networks, Support Vector Machines (SVM), and clustering algorithms, which are sensitive to differences in feature scales.

As a result, normalization improves model performance, speeds up convergence during training, and ensures a more balanced analysis of the data. In this project, Min-Max normalization was applied to the salary column, creating a normalized salary feature with values ranging from 0 to 1.

Principal Component Analysis (PCA)

One of the most commonly used dimensionality reduction techniques is Principal Component Analysis (PCA).

PCA:

Identifies the directions (principal components) that capture the greatest variance in the data.
Transforms the original features into a smaller set of new features called principal components.
Retains most of the important information while reducing the number of dimensions.
Helps minimize data redundancy and improve computational efficiency.

By applying PCA, analysts can simplify datasets, reduce noise, and maintain the essential patterns needed for effective machine learning and data analysis.

Data Aggregation by Experience Level

Data aggregation is the process of summarizing and combining data to identify patterns, trends, and insights within specific groups of a dataset. By grouping data based on a particular category, such as experience level, it becomes easier to analyze and compare information.

Benefits of Data Aggregation
Identifies Trends: Helps reveal patterns and relationships within different groups.
Simplifies Analysis: Summarizes large datasets into meaningful statistics.
Supports Decision-Making: Provides insights that can guide business and organizational strategies.
Facilitates Comparisons: Makes it easier to compare metrics across categories.
Salary Analysis by Experience Level

Grouping the dataset by the experience_level column and calculating salary statistics can provide valuable insights into compensation patterns.

Common aggregation measures include:

Average Salary (Mean): Shows the typical salary earned at each experience level.
Median Salary: Represents the middle salary value and is less affected by extreme values or outliers.
Insights Gained from Aggregation

By calculating the average and median salaries for each experience level (e.g., Junior, Mid-level, Senior, Executive), you can:

Understand how salaries increase with experience.
Identify compensation differences between job levels.
Detect salary distribution patterns and potential outliers.
Evaluate whether salary growth is consistent across career stages.
Answer business questions such as:
How does salary evolve with experience?
What is the typical salary range for senior-level professionals?
Are there significant salary disparities between experience levels?

Aggregating salary data by experience level provides a clear view of compensation trends and helps organizations, job seekers, and analysts make informed decisions based on workforce and salary insights.
"""